// C-ERR

func main() {
    print(!4)
}