// P-ERR

func main() {}

extern func bad() = 2 + 2 == 5